# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    configs:
        flat_config:
            toolbar: 'flat_toolbar'
    toolbars:
        configs:
            flat_toolbar: ['@full.clipboard', '@full.basic_styles', '@full.insert', '@full.links', '@full.document', '@full.editing', '@full.paragraph', '@full.styles', '@full.tools', '@full.about']
        items:
            full.insert: [ 'Table' ]
            full.links: [ 'Link', 'Unlink' ]
            full.document: [ '-', 'NewPage', 'Preview', 'Print', '-', 'Templates' ]