version: '3.8'

services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=flatapp
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    tty: true
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - php
      - database